-- ============================================
-- MINIMAL SCHEMA: Create vetted_projects table
-- Run this in Supabase SQL Editor
-- ============================================

-- Enable UUID extension (if not already enabled)
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create vetted_projects table
CREATE TABLE IF NOT EXISTS public.vetted_projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- From Vetted webhook payload
    vetted_project_id UUID UNIQUE NOT NULL,
    project_title TEXT NOT NULL,
    recruiter_email TEXT NOT NULL,
    recruiter_name TEXT,
    
    -- Generated by Congrats
    audition_url TEXT NOT NULL,
    
    -- Tracking & Status
    status TEXT DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Stats
    total_submissions INTEGER DEFAULT 0,
    last_submission_at TIMESTAMPTZ
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_vetted_projects_status ON public.vetted_projects(status);
CREATE INDEX IF NOT EXISTS idx_vetted_projects_created_at ON public.vetted_projects(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vetted_projects_recruiter_email ON public.vetted_projects(recruiter_email);
CREATE INDEX IF NOT EXISTS idx_vetted_projects_vetted_id ON public.vetted_projects(vetted_project_id);

-- Enable Row Level Security
ALTER TABLE public.vetted_projects ENABLE ROW LEVEL SECURITY;

-- Policy: Anyone can view active projects (for public audition URLs)
CREATE POLICY "Anyone can view active projects"
    ON public.vetted_projects
    FOR SELECT
    USING (status = 'active');

-- Policy: Service role can insert projects (from webhook)
CREATE POLICY "Service role can create projects"
    ON public.vetted_projects
    FOR INSERT
    WITH CHECK (true);

-- Policy: Recruiters can view their own projects
CREATE POLICY "Recruiters can view own projects"
    ON public.vetted_projects
    FOR SELECT
    USING (recruiter_email = current_setting('request.jwt.claims', true)::json->>'email');

-- Create trigger for updated_at
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_vetted_projects_updated_at
    BEFORE UPDATE ON public.vetted_projects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- DONE! Now test your webhook
-- ============================================
