
// Mock data to simulate backend response
const mockProject = {
    id: '550e8400-e29b-41d4-a716-446655440000',
    role_title: 'Software Engineer',
    company_name: 'Tech Corp'
};

const mockRoleDefinition = {
    id: 'role-def-id-123',
    project_id: '550e8400-e29b-41d4-a716-446655440000',
    definition_data: {
        candidate_facing_jd: {
            role_title: 'Software Engineer'
        }
    }
};

// Logic from Jobs.tsx
function generateSlugFromProject(project) {
    return (project.role_title || 'untitled')
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '') + '-' + project.id.substring(0, 8);
}

// Logic from JobDetail.tsx (Updated)
function matchSlug(slug, roleDef) {
    if (!roleDef.definition_data?.candidate_facing_jd) return false;
    const jd = roleDef.definition_data.candidate_facing_jd;
    const generatedSlug = jd.role_title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/^-+|-+$/g, '') + '-' + (roleDef.project_id || roleDef.id).substring(0, 8);

    console.log(`Comparing: ${slug} vs ${generatedSlug}`);
    return generatedSlug === slug;
}

// Verification
console.log('--- Verifying Slug Matching Logic ---');

const listingSlug = generateSlugFromProject(mockProject);
console.log(`Slug generated by Listing (Jobs.tsx): ${listingSlug}`);

const isMatch = matchSlug(listingSlug, mockRoleDefinition);

if (isMatch) {
    console.log('✅ SUCCESS: JobDetail logic correctly matches the slug!');
} else {
    console.log('❌ FAILURE: JobDetail logic failed to match the slug.');
    process.exit(1);
}
