-- ============================================
-- CONGRATS AI - AUDITIONS DATABASE SCHEMA
-- Separate Supabase Project for Audition System
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- TABLE: vetted_projects
-- Stores projects received from Vetted via webhook
-- Links recruiters to their auditions
-- ============================================
CREATE TABLE IF NOT EXISTS public.vetted_projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- From Vetted webhook payload
    vetted_project_id UUID UNIQUE NOT NULL,  -- Vetted's project ID (used in audition URL)
    project_title TEXT NOT NULL,
    recruiter_email TEXT NOT NULL,
    recruiter_name TEXT,
    
    -- Generated by Congrats
    audition_url TEXT NOT NULL,  -- The URL we send back to recruiter
    
    -- Tracking & Status
    status TEXT DEFAULT 'active', -- 'active', 'closed', 'archived'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Submission stats (optional, can be computed)
    total_submissions INTEGER DEFAULT 0,
    last_submission_at TIMESTAMPTZ
);

-- Indexes for vetted_projects
CREATE INDEX IF NOT EXISTS idx_vetted_projects_status ON public.vetted_projects(status);
CREATE INDEX IF NOT EXISTS idx_vetted_projects_created_at ON public.vetted_projects(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_vetted_projects_recruiter_email ON public.vetted_projects(recruiter_email);
CREATE INDEX IF NOT EXISTS idx_vetted_projects_vetted_id ON public.vetted_projects(vetted_project_id);

-- ============================================
-- TABLE: audition_submissions
-- Stores user submissions for auditions
-- Links candidates to vetted_projects
-- ============================================
CREATE TABLE IF NOT EXISTS public.audition_submissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL, -- From main auth system
    vetted_project_id UUID NOT NULL REFERENCES public.vetted_projects(vetted_project_id) ON DELETE CASCADE,
    
    -- Submission data
    questions JSONB NOT NULL, -- Array of question texts submitted
    audio_urls JSONB NOT NULL, -- Array of {question_index, audio_url, file_path}
    
    -- Metadata
    status TEXT DEFAULT 'pending', -- 'pending', 'reviewing', 'approved', 'rejected'
    submitted_at TIMESTAMPTZ DEFAULT NOW(),
    reviewed_at TIMESTAMPTZ,
    reviewer_id UUID, -- Who reviewed it
    
    -- Additional info
    duration_seconds INTEGER, -- Total time taken
    user_agent TEXT, -- Browser info for tracking
    ip_address TEXT, -- For security
    
    -- Constraints
    UNIQUE(user_id, vetted_project_id) -- One submission per user per project
);

-- Indexes for queries
CREATE INDEX IF NOT EXISTS idx_submissions_user_id ON public.audition_submissions(user_id);
CREATE INDEX IF NOT EXISTS idx_submissions_vetted_project_id ON public.audition_submissions(vetted_project_id);
CREATE INDEX IF NOT EXISTS idx_submissions_status ON public.audition_submissions(status);
CREATE INDEX IF NOT EXISTS idx_submissions_submitted_at ON public.audition_submissions(submitted_at DESC);

-- ============================================
-- TABLE: proctoring_snapshots
-- Stores camera snapshots for proctoring
-- ============================================
CREATE TABLE IF NOT EXISTS public.proctoring_snapshots (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    submission_id UUID NOT NULL REFERENCES public.audition_submissions(id) ON DELETE CASCADE,
    snapshot_url TEXT NOT NULL, -- URL to image in storage
    captured_at TIMESTAMPTZ DEFAULT NOW(),
    metadata JSONB -- Additional data like device info
);

-- Index for lookups
CREATE INDEX IF NOT EXISTS idx_proctoring_submission_id ON public.proctoring_snapshots(submission_id);

-- ============================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- ============================================

-- Enable RLS on all tables
ALTER TABLE public.vetted_projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audition_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proctoring_snapshots ENABLE ROW LEVEL SECURITY;

-- VETTED_PROJECTS POLICIES
-- Anyone can view active projects (for public audition URLs)
CREATE POLICY "Anyone can view active projects"
    ON public.vetted_projects
    FOR SELECT
    USING (status = 'active');

-- Service role can insert projects (from webhook)
CREATE POLICY "Service role can create projects"
    ON public.vetted_projects
    FOR INSERT
    WITH CHECK (true);  -- Webhook uses service role key

-- Recruiters can view their own projects
CREATE POLICY "Recruiters can view own projects"
    ON public.vetted_projects
    FOR SELECT
    USING (recruiter_email = current_setting('request.jwt.claims', true)::json->>'email');

-- SUBMISSIONS POLICIES
-- Users can view their own submissions
CREATE POLICY "Users can view own submissions"
    ON public.audition_submissions
    FOR SELECT
    USING (auth.uid() = user_id);

-- Users can insert their own submissions
CREATE POLICY "Users can create own submissions"
    ON public.audition_submissions
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Users cannot update submissions after creation (immutable)
-- Admins would need service role to update

-- PROCTORING POLICIES
-- Users can view snapshots for their submissions
CREATE POLICY "Users can view own proctoring snapshots"
    ON public.proctoring_snapshots
    FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM public.audition_submissions
            WHERE audition_submissions.id = proctoring_snapshots.submission_id
            AND audition_submissions.user_id = auth.uid()
        )
    );

-- ============================================
-- STORAGE BUCKETS (Run in Supabase Dashboard)
-- ============================================

-- Create storage bucket for audio recordings
-- Run this in Supabase SQL Editor:
/*
INSERT INTO storage.buckets (id, name, public)
VALUES ('audition-recordings', 'audition-recordings', false)
ON CONFLICT (id) DO NOTHING;
*/

-- Storage policies for audio recordings
-- Users can upload to their own folder
/*
CREATE POLICY "Users can upload own recordings"
    ON storage.objects
    FOR INSERT
    WITH CHECK (
        bucket_id = 'audition-recordings'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

CREATE POLICY "Users can view own recordings"
    ON storage.objects
    FOR SELECT
    USING (
        bucket_id = 'audition-recordings'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );
*/

-- ============================================
-- SEED DATA - Sample Vetted Projects (Optional)
-- Comment out if you only want real data from Vetted webhook
-- ============================================

-- Example seed data (commented out - use real data from Vetted)
-- VALUES 
--     (
--         'a1b2c3d4-e5f6-7890-abcd-ef1234567890'::uuid,
--         'Backend Engineer',
--         'recruiter@vetted.ai',
--         'Jane Doe',
--         'https://talent.vettedai.app/audition/a1b2c3d4-e5f6-7890-abcd-ef1234567890/start',
--         'active'
--     )
-- ON CONFLICT DO NOTHING;

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Trigger for vetted_projects table
CREATE TRIGGER update_vetted_projects_updated_at
    BEFORE UPDATE ON public.vetted_projects
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- VIEWS (Optional - for easier queries)
-- ============================================

-- View for submissions with project details
CREATE OR REPLACE VIEW public.submissions_with_projects AS
SELECT 
    s.id,
    s.user_id,
    s.vetted_project_id,
    s.status,
    s.submitted_at,
    s.reviewed_at,
    p.project_title,
    p.recruiter_email,
    p.recruiter_name,
    p.audition_url,
    s.audio_urls,
    s.questions
FROM public.audition_submissions s
JOIN public.vetted_projects p ON s.vetted_project_id = p.vetted_project_id;

-- ============================================
-- COMPLETED!
-- ============================================

-- To apply this schema:
-- 1. Go to your Supabase project dashboard
-- 2. Navigate to SQL Editor
-- 3. Copy and paste this entire file
-- 4. Click "Run"
-- 5. Verify all tables are created in the Table Editor
